### ISSUE TITLE
Use khaos.

### ISSUE THREAD

**Issue by imlucas** [mongodb-js/mj#2]
Use github.com/segment/khaos as a lib like https://github.com/logo/cli/blob/master/bin/logo-create

Also read this blog post https://segment.com/blog/building-building-blocks/

**Comment by rueckstiess** [comment]
List of potential templates we would want:
- empty: an empty directory structure with the bare minimum to qualify as mongodb-js
- cli: command-line interface app with docopt, like "mj". 
- view: an ampersand view module, e.g. a subview for a larger app (object-tree, minicharts, ...)
- spa: single-page application, running entirely in a browser (wtstats, kaleido, ...)
- full: full client/server app (e.g. scout, dashboards, ...)
- shell: a mongo shell plugin with automatic registration
- util: a utility function, template or code snippet (mixins, etc)
- doc: a non-code document, spec or documentation

**Comment by rueckstiess** [comment]
dependency graph. 

![image](https://cloud.githubusercontent.com/assets/99221/8249057/b9b468d2-16a9-11e5-9dee-d74a0ef17b68.png)

**Comment by rueckstiess** [comment]
@imlucas what do you think is better: 

a) have all our khaos templates as individual repos in mongodb-js
b) have all our khaos templates in ONE repo (mj-templates or something)
c) have them nowhere but directly included in mj under `./templates/*`

I kind of like to avoid a) because it pollutes the repository a lot and these templates kind of belong together. segment also embed some templates directly inside certain tools, like the logo creation thing.

**Comment by imlucas** [comment]
@rueckstiess agree on embedding templates under `mj/templates/*`.  Perhaps we could consolidate your list of templates + graph above somewhere to include our previous attempt at this? (see Templates section in description) https://github.com/mongodb-js/mj/issues/4

**Comment by rueckstiess** [comment]
Yes lets consolidate the tickets. Closing this and moving everything over to #4.
